# GitLab CI/CD Pipeline for Self-Service Kiosk
# Automated build, test, and deployment pipeline

stages:
  - build
  - test
  - deploy

variables:
  DOCKER_IMAGE: $CI_REGISTRY_IMAGE
  DOCKER_TAG: $CI_COMMIT_SHORT_SHA
  CONTAINER_NAME: self-service-kiosk

# Build stage
build:
  stage: build
  image: docker:24.0.5
  services:
    - docker:24.0.5-dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - echo "🏗️ Building Docker image..."
    - docker build 
        --build-arg VITE_API_BASE_URL=$VITE_API_BASE_URL 
        -t $DOCKER_IMAGE:$DOCKER_TAG 
        -t $DOCKER_IMAGE:latest .
    - echo "📤 Pushing to registry..."
    - docker push $DOCKER_IMAGE:$DOCKER_TAG
    - docker push $DOCKER_IMAGE:latest
  only:
    - main
    - develop
  tags:
    - docker

# Test stage
test:
  stage: test
  image: node:20-alpine
  cache:
    paths:
      - frontend/node_modules/
  before_script:
    - cd frontend
    - npm ci
  script:
    - echo "🧪 Running tests..."
    - npm run build
    - echo "✅ Build test passed"
  only:
    - main
    - develop
    - merge_requests

# Deploy to production
deploy_production:
  stage: deploy
  image: docker:24.0.5
  services:
    - docker:24.0.5-dind
  environment:
    name: production
    url: https://self-service-kiosk.givemebug.online
  before_script:
    - apk add --no-cache curl make
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - echo "🚀 Deploying to production..."
    - make deploy
    - echo "⏳ Waiting for health check..."
    - sleep 30
    - curl -f https://self-service-kiosk.givemebug.online/health
    - echo "✅ Deployment successful!"
  after_script:
    - echo "🧹 Cleaning up old images..."
    - docker image prune -f
  only:
    - main
  when: manual
  tags:
    - docker

# Deploy to staging
deploy_staging:
  stage: deploy
  image: docker:24.0.5
  services:
    - docker:24.0.5-dind
  environment:
    name: staging
    url: https://staging.self-service-kiosk.givemebug.online
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - echo "🚀 Deploying to staging..."
    - export DOMAIN=staging.self-service-kiosk.givemebug.online
    - make deploy
  only:
    - develop
  tags:
    - docker